### ISSUE TITLE
ActiveRecord Depreciation Warning

### ISSUE THREAD

**Issue by edude03** [betterup/wisper-activerecord-publisher#2]
Hello, I've been using your gem and it's better great so far, however I've run into a minor issue. It seems that because the gem causes ActiveRecord to be loaded before the application configuration users of Rails 4.2 run into this depreciation warning

```
DEPRECATION WARNING: Currently, Active Record suppresses errors raised within `after_rollback`/`after_commit` callbacks and only print them to the logs. In the next version, these errors will no longer be suppressed. Instead, the errors will propagate normally just like in other Active Record callbacks.

You can opt into the new behavior and remove this warning by setting:

  config.active_record.raise_in_transactional_callbacks = true

 (called from <top (required)> at /app/config/application.rb:7)
```

My application.rb (and I imagine most people's looks like this

``` ruby
7: Bundler.require(*Rails.groups)
8: 
9: module MyApp
10:  class Application < Rails::Application
```

Is there a way to defer the loading of this gem until after the application has been initialized?

**Comment by wireframe** [comment]
I haven't found a way to silence these messages in Rails 4.2, but these messages are no longer shown after upgrading to Rails 5.

If you have a pull request for Rails 4.2, I'd happily accept it.

**Comment by edude03** [comment]
Apparently there is a simple solution :)
